### ISSUE TITLE
Перебои работы Интернета в Москве (МГТС) 13:15 - ...

### ISSUE THREAD

**Issue by NetBUG** [podivilov/runet-blackout#16]
Наблюдаются проблемы с доступом к pikabu.ru, причём как из российской сети, так и с использованием VPN до шлюза во Франции. В итоге ресурс доступен с задержкой ~1 минута на запрос.
DNS - OpenDNS.
#partial inaccessibility

**Comment by podivilov** [comment]
@NetBUG, возможно, проблема с самим ресурсом pikabu.ru.

**Comment by f14a2cd** [comment]
> pikabu.ru

http отвечает за 80 мск, https не ответил за 10

Тут два варианта - либо dpi, либо сам пикабу

**Comment by podivilov** [comment]
> > pikabu.ru
> 
> http отвечает за 80 мск, https не ответил за 10
> 
> Тут два варианта - либо dpi, либо сам пикабу
> 
> https://sitestatus.ru/?url=https%3A%2F%2Fpikabu.ru%2F

Скорее всего с их сервером проблемы. Метка есть у issue.

**Comment by f14a2cd** [comment]
Пикабу стал по нормальному таймингу отвечать, можно закрывать

**Comment by podivilov** [comment]
Закрываю.
