### ISSUE TITLE
Перебои работы Сервиса РСА

### ISSUE THREAD

**Issue by Jugador1991** [podivilov/runet-blackout#17]
Сервисы РСА переодически не доступны, не работают АИС ЕАИСТО
Оформление Осаго временно невозможно

**Comment by podivilov** [comment]
@Jugador1991, пожалуйста, сообщите начало время сбоя, ваш город и название провайдера.

**Comment by Jugador1991** [comment]
Сбой не у моего провайдера, а у провайдера РСА. 
На данный момент не доступно.  Bad request
ЕАИСТО обслуживается и создано РСА, и скорее всего проходит учения вместе с МВД

**Comment by Jugador1991** [comment]
Вот пример ссылки на оформление полиса у РСА
http://egarant.autoins.ru/egarant-web-1.0/insuranceCompany.htm?DraftPolicyId=2881484035
Сам кабинет открывается, но вот расчет страховой премии, проверка ТО и т.д. не происходит т.к. само рса не может достучаться до своих сервисов, и висит вот такая ошибка:

СООБЩАЕМ О НЕВОЗМОЖНОСТИ ОФОРМЛЕНИЯ ДОГОВОРА ОСАГО В ВИДЕ ЭЛЕКТРОННОГО ДОКУМЕНТА ПО ПРИЧИНЕ ОТСУТСТВИЯ ОТВЕТА ИЗ ЕДИНОЙ АВТОМАТИЗИРОВАННОЙ ИНФОРМАЦИОННОЙ СИСТЕМЫ ТЕХНИЧЕСКОГО ОСМОТРА. ПРЕДЛАГАЕМ ПОВТОРНО НАПРАВИТЬ ЗАЯВЛЕНИЕ О ЗАКЛЮЧЕНИИ ДОГОВОРА ОСАГО В ВИДЕ ЭЛЕКТРОННОГО ДОКУМЕНТА ПОСЛЕ ВОССТАНОВЛЕНИЯ РАБОТОСПОСОБНОСТИ ЕДИНОЙ АВТОМАТИЗИРОВАННОЙ ИНФОРМАЦИОННОЙ СИСТЕМЫ ТЕХНИЧЕСКОГО ОСМОТРА

**Comment by f14a2cd** [comment]
![image](https://user-images.githubusercontent.com/57997247/71359248-9e157e00-25ad-11ea-9005-1d2dd2a790b3.png)

Может у самого сервиса отвал? Техработы там?

**Comment by podivilov** [comment]
> ![image](https://user-images.githubusercontent.com/57997247/71359248-9e157e00-25ad-11ea-9005-1d2dd2a790b3.png)
> 
> Может у самого сервиса отвал? Техработы там?

Вполне возможно, но если бы 500 возвращался без HTTPS, то вполне вероятно можно было бы предположить MITM.

**Comment by Jugador1991** [comment]
Не, началось утром, потом чутка поработало. потом стали отваливаться разные сервисы.
Сначала ЕАИСТО. потом не рассчитывало сам полис.
Потом все опять заработало. и опять отвалилось.
А тех работы назначены на завтра, на  главное странице висит плашка по этому поводу

**Comment by podivilov** [comment]
> Не, началось утром, потом чутка поработало. потом стали отваливаться разные сервисы.
> Сначала ЕАИСТО. потом не рассчитывало сам полис.
> Потом все опять заработало. и опять отвалилось.
> А тех работы назначены на завтра, на главное странице висит плашка по этому поводу

Может, это всё-таки с их сервами проблемы? Такое бывает.

**Comment by UndeadJoe** [comment]
> ![image](https://user-images.githubusercontent.com/57997247/71359248-9e157e00-25ad-11ea-9005-1d2dd2a790b3.png)
> 
> Может у самого сервиса отвал? Техработы там?

500 код ошибки означает, что ответ от конечного сервера пришел в целостности. Это ошибка самого сервиса РСА, а не каналов связи до него.

**Comment by podivilov** [comment]
@UndeadJoe прав, это проблема с сервисом. Закрываю.

**Comment by Jugador1991** [comment]
>Может, это всё-таки с их сервами проблемы? Такое бывает.
Можете предоставить пруфы?

Зачем вы вообще затеяли всю эту шляпу с тикетами, елси по своему мнению решаете проблемы с сервисом это или нет? 

ЕАИСТО это структура МВД. Лежит она с утра 23 числа.

РСа работает, кабинеты работают, но внутри ошибка, ЕАИСТО не доступен.

**Comment by podivilov** [comment]
@Jugador1991 500 - это код ошибки сервера.

**Comment by Jugador1991** [comment]
Я знаю, что такое 500 код.
Но действующие кабинеты работают без 500 кода. Зато внутри другое.
СК тоже не могут достучаться до ЕАИСТО. Оно то работает, то нет, ответ BAD request

**Comment by podivilov** [comment]
@Jugador1991, 500 код - это ответ веб-сервера, что тот не может обработать страницу. Это значит, что соединение есть, так как HTTP работает на 7 уровне модели OSI.

**Comment by Jugador1991** [comment]
![502](https://user-images.githubusercontent.com/19787121/71360063-45a8a580-25da-11ea-8501-dc4f4bb0dac5.jpg)

А это?

**Comment by podivilov** [comment]
@Jugador1991, 502 - это код ответа веб-сервера.

**Comment by Jugador1991** [comment]
Вообщем я не представляю, как вы предлагаете проверить недоступность одного сервиса МВД для другого сервиса, не явившись в ДЦ. соотв пруфов тут не будет никогда, как и сообственно в других тикетах.

502 и 500 это по сути maintenance mode  для РСА.
т.к. после того как отвалился ЕАИСТО, они работали, а учитывая поток в сотни тысяч осаго в минуту, через мин 20 они отключили все полностью.
Сейчас опять работает, но опять для рса сервисы не доступны. (соединение между РСА и МВД).

Вообщем тут уже дело каждого, думатьв  чем причина. пусть будет неожиданная поломка 23 утром.)

**Comment by UndeadJoe** [comment]
> А это?

Это тоже ответ от конечного сервера. Только в случае 502 nginx не смог проксировать запрос дальше. А по какой причине и куда это уже внутренности, о которых не узнать. Скорее всего если сервер начал выдавать много 500 ошибок, то система мониторинга (контроля) отправила его в перезагрузку, чем и вызвала 502.
