### ISSUE TITLE
Перебои работы Интернета в [Москва (Мой Онлайм)] [00:00 — 00:15]

### ISSUE THREAD

**Issue by Sild** [podivilov/runet-blackout#25]
* Сеть не работала полностью от роутера и дальше
![photo_2019-12-23_18-12-40](https://user-images.githubusercontent.com/1629069/71365421-ffd6e780-25af-11ea-90ed-21279939f8e1.jpg)
![photo_2019-12-23_18-12-28](https://user-images.githubusercontent.com/1629069/71365423-02394180-25b0-11ea-9028-28327a847fd0.jpg)

**Comment by f14a2cd** [comment]
@podivilov закрывай, это траблы на станции у провайдера
