### ISSUE TITLE
12.23.2019 from 9:00am, Saint-Petersburg: https://pochtabank.ru (504)

### ISSUE THREAD

**Issue by MrTobikun** [podivilov/runet-blackout#26]

**Comment by MrTobikun** [comment]
![](https://i.imgur.com/TA2L922.jpg)

**Comment by f14a2cd** [comment]
![изображение](https://user-images.githubusercontent.com/57997247/71374967-80144180-25de-11ea-80ce-9dc981799eba.png)
Москва, МГТС

**Comment by MrTobikun** [comment]
![](https://i.imgur.com/nexoibR.jpg)

**Comment by MrTobikun** [comment]
![](https://i.imgur.com/nexoibR.jpg)

**Comment by MrTobikun** [comment]
![](https://i.imgur.com/nexoibR.jpg)

**Comment by f14a2cd** [comment]
Ты че делаешь, ирод?

**Comment by MrTobikun** [comment]
Tele2 Mobile

**Comment by f14a2cd** [comment]
```f14@2cd:~/work/base/busgov$ ping pochtabank.ru
PING pochtabank.ru (91.216.147.7) 56(84) bytes of data.
^C
--- pochtabank.ru ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4079ms

f14@2cd:~/work/base/busgov$ ```

Ты уверен, что он и ранее на пинг отвечал?

**Comment by f14a2cd** [comment]
Вышли скриншот, если это так

**Comment by slomonosov** [comment]
Отсутствует ping из сетей Beeline (ru, скрин 1) и Hetzner (de, скрин 2), но тем не менее открывается

* Beeline
![pochtabank-beeline](https://user-images.githubusercontent.com/9397721/71375516-8d75ff80-25cf-11ea-9829-b423a030e0cc.PNG)

* Hetzner

![pochtabank-hetzner](https://user-images.githubusercontent.com/9397721/71375535-9e267580-25cf-11ea-9981-55dc008460cc.PNG)

![allinone](https://user-images.githubusercontent.com/9397721/71375580-cf9f4100-25cf-11ea-902d-9b66a3e77f58.PNG)

**Comment by f14a2cd** [comment]
Тут стоит Anti-DDoS от МТСа (что видно по ipinfo). МТС кривожопами всегда были,и они не пропускают **ping** на свое оборудование
