### ISSUE TITLE
Перебои работы Интернета в [Москва (Акадо)] (Cloudflare)

### ISSUE THREAD

**Issue by cora32** [podivilov/runet-blackout#37]
На данный момент, полная недоступность (Connection timed out) всех ipv4-диапазонов, кроме одного (104.16.0.0/12) сети Cloudflare.

![err](https://user-images.githubusercontent.com/8068953/71412856-8d721000-2660-11ea-8408-d49b0a8570aa.jpg)
_Скрин для одного адреса, но ситуация аналогичная для всех адресов из списка https://www.cloudflare.com/ips-v4, кроме "избранного"._

**Comment by podivilov** [comment]
Смотрите списки Роскомнадзора.
